name: Deploy to Environment

run-name: run environment by - ${{inputs.TARGET}}

on: 
  workflow_dispatch:
    inputs:
      TARGET:
        type: environment
        required: true
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.TARGET }}
    steps: 
      - name: Deploy to ${{ inputs.TARGET }}
        run: |
          echo "Selected env - ${{ inputs.TARGET }}"
          echo "Selected config - ${{ vars.CONFIG }}"       
