name: CI/CD Filters Pipeline

on:
  push:
    branches:
      - master
      - 'release/*'
      - '!feature/*'

    tags:
      - 'v*.*.*'

    paths:
      - 'src/**'
      - '!docs/**'

  pull_request:
    types: [opened]

jobs:
  run-job-filters:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Log date
        run: echo date  # Print the timestamp
