name: Log GitHub Context and Set Environment Variable

on:
  push:
    branches:
      - master
      - development

jobs:
  log-context:
    runs-on: ubuntu-latest

    steps:
      
      - name: Log GitHub context values
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "Event Name: ${{ github.event_name }}"

      - name: Set GIT_BRANCH environment variable
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "GIT_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/development" ]]; then
            echo "GIT_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "GIT_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Print GIT_BRANCH
        run: echo "GIT_BRANCH is $GIT_BRANCH"
