name: Matrix Workflow

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [19, 20, 21]
        os: [ubuntu-latest, windows-latest]
        include:
          - node: 21
            os: macos-latest
        exclude:
          - node: 19
            os: windows-latest
            
    steps:
      - name: Display Timestamp
        run: echo date
