name: Hello World
run-name: ${{ github.actor }}

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Display "Hello World"
      run: echo "Hello World"

    - name: Display "DateTime"
      run: date
