name: Hello World
run-name: ${{ github.actor }}

on: 
  pull_request_review:
    types: [edited]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Display "Hello World"
      run: echo "Hello World"
